# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\desktop\keyboard heatmap\about.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(616, 213)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(129, 20, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 531, 41))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(240, 150, 121, 41))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close) # type: ignore
        Form.destroyed.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "关于"))
        self.label.setText(_translate("Form", "本程序由狐小九Little_Jiu开发\n"
"感谢使用"))
        self.label_2.setText(_translate("Form", "<a href=\"https://github.com/Abyss-Reg/keyboard-heatmap\" style=\"font-size=10px; color:inherit\"><b>项目开源链接：https://github.com/Abyss-Reg/keyboard-heatmap</b></a>"))
        self.pushButton.setText(_translate("Form", "确认"))
